const storeKey = 'zhixing-tutor-students-v1';
let state = JSON.parse(localStorage.getItem(storeKey) || '{"students":[],"activeId":null}');
const $ = s => document.querySelector(s);
const cloudKey = 'zhixing-tutor-cloud-v1';
const supabaseClient = window.supabase?.createClient('https://nnnxsjqbklnykshqgntt.supabase.co','sb_publishable_SaQQauIlc5EJqG7IhKWQFw_mYctgZiR');
let cloud = JSON.parse(localStorage.getItem(cloudKey) || '{"auto":true,"lastSync":null,"userEmail":""}');
let authRegister = false;
let autoSyncTimer;
let realtimeChannel;
const save = (scheduleCloud=true) => { state.updatedAt = new Date().toISOString(); localStorage.setItem(storeKey, JSON.stringify(state)); if(scheduleCloud && cloud.auto && cloud.userEmail){clearTimeout(autoSyncTimer);autoSyncTimer=setTimeout(()=>syncCloud('push',true),1200)} };
const esc = v => String(v || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const active = () => state.students.find(s => s.id === state.activeId);
const initials = name => (name || '?').trim().slice(0,2);
const today = () => new Date().toISOString().slice(0,10);
const appRedirectUrl = new URL('./', window.location.href).href;
function downloadStoredFile(file){return()=>{if(!file.data){alert('这是旧版本记录的附件名称，请重新添加文件。');return}const link=document.createElement('a');link.href=file.data;link.download=file.name;link.click();}}

function renderList(){
  $('#studentCount').textContent = state.students.length;
  $('#studentList').innerHTML = state.students.map(s => `<button class="student-item ${s.id===state.activeId?'active':''}" data-id="${s.id}"><span class="avatar">${esc(initials(s.name))}</span><span>${esc(s.name)}<small>${esc(s.school || '未填写学校')}</small></span></button>`).join('');
  document.querySelectorAll('.student-item').forEach(b=>b.onclick=()=>{state.activeId=b.dataset.id;save();render();});
}
function render(){
  renderSyncStatus();
  const signedIn=!!cloud.userEmail;
  document.body.classList.toggle('logged-out',!signedIn);
  if(!signedIn){$('#emptyState').hidden=false;$('#studentView').hidden=true;return}
  if(!active()&&state.students.length){state.activeId=state.students[0].id;save(false)}
  renderList(); const s=active(); $('#emptyState').hidden=true; $('#studentView').hidden=!s; if(!s)return;
  $('#studentNameTitle').textContent=s.name; $('#studentMeta').textContent=`${s.school || '未填写学校'} · 学生档案`;
  $('#schoolText').textContent=s.school || '待补充'; $('#targetSchoolText').textContent=s.targetSchool || '待补充';
  $('#currentScore').textContent=s.currentScore ?? '—'; $('#targetScore').textContent=s.targetScore ?? '—';
  const currentNumber=parseFloat(s.currentScore),targetNumber=parseFloat(s.targetScore);const scoreRatio=targetNumber?Math.max(0,Math.min(100,Math.round((currentNumber||0)/targetNumber*100))):0; $('#scoreRing').style.setProperty('--p',scoreRatio+'%');
  $('#goalHint').textContent=targetNumber ? `距离目标还差 ${Math.max(0,targetNumber-(currentNumber||0))} 分` : '自由填写你的分数目标';
  $('#nextLesson').value=s.nextLesson||''; $('#focusContent').value=s.focusContent||'';
  $('#customFields').innerHTML=(s.custom||[]).map((f,i)=>`<div class="custom-field"><span>${esc(f.key)}</span><strong>${esc(f.value)}</strong><button class="remove-custom" data-i="${i}" title="删除">×</button></div>`).join('')||'<div class="no-data" style="position:static;display:block;text-align:left">添加需要长期记录的信息</div>';
  document.querySelectorAll('.remove-custom').forEach(b=>b.onclick=()=>{s.custom.splice(+b.dataset.i,1);save();render();});
  const scores=(s.scores||[]).slice().sort((a,b)=>a.date.localeCompare(b.date));
  $('#scoreHistory').innerHTML=scores.map((x,i)=>`<span class="score-chip">${esc(x.label)} <b>${x.score}</b> <button class="remove-score" data-i="${i}" title="删除">×</button></span>`).join('');
  document.querySelectorAll('.remove-score').forEach(b=>b.onclick=()=>{const original=scores[+b.dataset.i];s.scores.splice(s.scores.indexOf(original),1);save();render();});
  const course=(s.courseProgress||[]); $('#courseList').innerHTML=course.map((item,i)=>`<article class="prep-item"><div class="prep-item-head"><div><h3>${esc(item.title||item.text)}</h3><time>${esc(item.date)}</time></div><button class="remove-course" data-i="${i}" type="button" aria-label="删除该条进度">×</button></div>${item.content?`<p>${esc(item.content).replace(/\n/g,'<br>')}</p>`:''}${item.files?.length?`<div class="prep-files">${item.files.map((file,j)=>`<button class="prep-file course-file" data-i="${i}" data-file="${j}" type="button" title="下载 ${esc(file.name)}">⌁ ${esc(file.name)}</button>`).join('')}</div>`:''}</article>`).join('')||'<p class="course-empty">还没有课程进度。点击“添加进度”开始记录。</p>';
  document.querySelectorAll('.remove-course').forEach(b=>b.onclick=()=>{if(confirm('删除这条课程进度吗？')){course.splice(+b.dataset.i,1);s.courseProgress=course;save();render();}});
  document.querySelectorAll('.course-file').forEach(b=>downloadStoredFile(course[+b.dataset.i].files[+b.dataset.file]));
  const preparations=s.preparations||[];$('#prepList').innerHTML=preparations.map((item,i)=>`<article class="prep-item"><div class="prep-item-head"><div><h3>${esc(item.title)}</h3><time>${esc(item.date)}</time></div><div class="item-actions"><button class="edit-prep" data-i="${i}" type="button">编辑</button><button class="remove-prep" data-i="${i}" type="button" aria-label="删除这次备课">×</button></div></div>${item.content?`<p>${esc(item.content).replace(/\n/g,'<br>')}</p>`:''}${item.files?.length?`<div class="prep-files">${item.files.map((file,j)=>`<button class="prep-file" data-i="${i}" data-file="${j}" type="button" title="下载 ${esc(file.name)}">⌁ ${esc(file.name)}</button>`).join('')}</div>`:''}</article>`).join('')||'<p class="course-empty">还没有备课条目。点击“添加备课”开始记录。</p>';
  document.querySelectorAll('.remove-prep').forEach(b=>b.onclick=()=>{if(confirm('删除这次备课吗？')){preparations.splice(+b.dataset.i,1);s.preparations=preparations;save();render();}});
  document.querySelectorAll('.edit-prep').forEach(b=>b.onclick=()=>openPrepEditor(+b.dataset.i));
  document.querySelectorAll('.prep-file:not(.course-file)').forEach(b=>b.onclick=downloadStoredFile(preparations[+b.dataset.i].files[+b.dataset.file]));
  $('#noScores').style.display=scores.length?'none':'grid'; drawChart(scores);
}
function drawChart(data){
  const canvas=$('#scoreChart'), wrap=canvas.parentElement, dpr=devicePixelRatio||1; const w=wrap.clientWidth,h=wrap.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);if(!data.length)return;
  const p={l:38,r:16,t:20,b:35}, vals=data.map(x=>Number(x.score));let min=Math.floor((Math.min(...vals)-5)/10)*10,max=Math.ceil((Math.max(...vals)+5)/10)*10;if(min===max){min-=10;max+=10};const X=i=>p.l+i*((w-p.l-p.r)/Math.max(1,data.length-1)),Y=v=>p.t+(max-v)/(max-min)*(h-p.t-p.b);
  c.font='11px DM Mono, monospace';c.textAlign='right';c.fillStyle='#8195aa';c.strokeStyle='#e5eef7';c.lineWidth=1;for(let i=0;i<4;i++){const val=min+(max-min)*i/3,y=Y(val);c.beginPath();c.moveTo(p.l,y);c.lineTo(w-p.r,y);c.stroke();c.fillText(Math.round(val),p.l-8,y+4)}
  const grad=c.createLinearGradient(0,p.t,0,h-p.b);grad.addColorStop(0,'rgba(31,111,235,.24)');grad.addColorStop(1,'rgba(31,111,235,0)');c.beginPath();data.forEach((x,i)=>i?c.lineTo(X(i),Y(x.score)):c.moveTo(X(i),Y(x.score)));c.lineTo(X(data.length-1),h-p.b);c.lineTo(X(0),h-p.b);c.closePath();c.fillStyle=grad;c.fill();
  c.beginPath();data.forEach((x,i)=>i?c.lineTo(X(i),Y(x.score)):c.moveTo(X(i),Y(x.score)));c.strokeStyle='#1f6feb';c.lineWidth=3;c.stroke();c.textAlign='center';data.forEach((x,i)=>{const px=X(i),py=Y(x.score);c.beginPath();c.arc(px,py,4,0,Math.PI*2);c.fillStyle='#b9dcff';c.fill();c.strokeStyle='#175da8';c.lineWidth=2;c.stroke();c.fillStyle='#647f9c';c.font='10px Manrope';c.fillText(x.label.length>6?x.label.slice(0,6)+'…':x.label,px,h-13);});
}
function openStudent(edit=false){const s=active();const f=$('#studentForm');f.reset();$('#studentDialogTitle').textContent=edit?'编辑学生资料':'添加学生';f.dataset.edit=edit?'1':'';if(edit&&s)Object.entries({name:s.name,school:s.school,targetSchool:s.targetSchool,currentScore:s.currentScore,targetScore:s.targetScore}).forEach(([k,v])=>f.elements[k].value=v??'');$('#studentDialog').showModal();}
$('#openStudentDialog').onclick=()=>openStudent();$('#emptyAddButton').onclick=()=>openStudent();$('#editStudentBtn').onclick=()=>openStudent(true);
function confirmCloseStudent(){if(confirm('确定关闭吗？尚未保存的填写内容将不会保留。'))$('#studentDialog').close('cancel')}
$('#closeStudentDialog').onclick=confirmCloseStudent;$('#cancelStudentDialog').onclick=confirmCloseStudent;
$('#studentDialog').addEventListener('cancel',e=>{e.preventDefault();confirmCloseStudent()});
$('#studentForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const f=e.currentTarget,d=Object.fromEntries(new FormData(f));const n={...d,currentScore:d.currentScore.trim()||null,targetScore:d.targetScore.trim()||null};if(f.dataset.edit){Object.assign(active(),n)}else{const s={id:crypto.randomUUID(),...n,scores:[],custom:[],courseProgress:[],preparations:[],nextLesson:'',focusContent:''};state.students.push(s);state.activeId=s.id}save();render();});
function openScore(){$('#scoreForm').reset();$('#scoreForm').elements.date.value=today();$('#scoreDialog').showModal()}$('#addScoreBtn').onclick=openScore;$('#noScoreButton').onclick=openScore;
$('#scoreForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const d=Object.fromEntries(new FormData(e.currentTarget)),score=Number(d.score.trim());if(!Number.isFinite(score)){e.preventDefault();alert('请输入有效的数字分数，例如 86 或 86.5。');return}active().scores.push({...d,score});active().currentScore=String(score);save();render();});
function closeCustomDialog(){$('#customDialog').close()}$('#addCustomBtn').onclick=()=>{$('#customForm').reset();$('#customDialog').showModal()};$('#closeCustomDialog').onclick=closeCustomDialog;$('#cancelCustomDialog').onclick=closeCustomDialog;$('#customForm').addEventListener('submit',e=>{const d=Object.fromEntries(new FormData(e.currentTarget));active().custom.push(d);save();render();});
function closePrepDialog(){$('#prepDialog').close()}function bufferToBase64(buffer){let binary='';const bytes=new Uint8Array(buffer);for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}async function prepFiles(files){const list=[...files];if(list.some(file=>file.size>2*1024*1024))throw new Error('单个附件不能超过 2MB');return Promise.all(list.map(async file=>({name:file.name,type:file.type||'application/octet-stream',size:file.size,data:`data:${file.type||'application/octet-stream'};base64,${bufferToBase64(await file.arrayBuffer())}`})))}function addPreparation({title,content='',files=[]}){const s=active();s.preparations=s.preparations||[];s.preparations.unshift({id:crypto.randomUUID(),title,content,files,date:new Date().toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})});save();render();}function openPrepEditor(index){const item=active().preparations[index],f=$('#prepForm');f.reset();f.dataset.editIndex=String(index);f.elements.title.value=item.title;f.elements.content.value=item.content||'';$('#prepFilesHint').textContent=item.files?.length?`已有 ${item.files.length} 个附件；新选择的文件会追加`:'可添加讲义、图片、PDF 等文件';$('#prepDialog').showModal()}
$('#addPrepBtn').onclick=()=>{const f=$('#prepForm');f.reset();delete f.dataset.editIndex;$('#prepFilesHint').textContent='可添加讲义、图片、PDF 等文件';$('#prepDialog').showModal()};$('#closePrepDialog').onclick=closePrepDialog;$('#cancelPrepDialog').onclick=closePrepDialog;
$('#prepForm').elements.files.onchange=e=>{$('#prepFilesHint').textContent=e.target.files.length?`已选择 ${e.target.files.length} 个文件（将记录文件名称）`:'可添加讲义、图片、PDF 等文件'};
$('#prepForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{const addedFiles=await prepFiles(f.elements.files.files),editIndex=f.dataset.editIndex;if(editIndex!==undefined){const item=active().preparations[+editIndex];Object.assign(item,{title:f.elements.title.value.trim(),content:f.elements.content.value.trim(),files:[...(item.files||[]),...addedFiles]});save();render();}else addPreparation({title:f.elements.title.value.trim(),content:f.elements.content.value.trim(),files:addedFiles});delete f.dataset.editIndex;closePrepDialog();}catch(err){alert(`保存失败：${err.message}`)}});
$('#importPrepBtn').onclick=()=>$('#prepImportInput').click();$('#prepImportInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{addPreparation({title:file.name.replace(/\.[^.]+$/,''),content:await file.text(),files:await prepFiles([file])});}catch{alert('该文档无法读取，或文件超过 2MB。请使用 TXT、Markdown 或纯文本文件。')}finally{e.target.value=''}};
function closeCourseDialog(){$('#courseDialog').close()}function addCourseItem({title,content='',files=[]}){const s=active();s.courseProgress=s.courseProgress||[];s.courseProgress.unshift({id:crypto.randomUUID(),title,content,files,date:new Date().toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})});save();render();}
$('#addCourseBtn').onclick=()=>{$('#courseItemForm').reset();$('#courseFilesHint').textContent='可添加作业、讲义、图片、PDF 等文件';$('#courseDialog').showModal()};$('#closeCourseDialog').onclick=closeCourseDialog;$('#cancelCourseDialog').onclick=closeCourseDialog;
$('#courseItemForm').elements.files.onchange=e=>{$('#courseFilesHint').textContent=e.target.files.length?`已选择 ${e.target.files.length} 个文件（可随档案下载）`:'可添加作业、讲义、图片、PDF 等文件'};
$('#courseItemForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{addCourseItem({title:f.elements.title.value.trim(),content:f.elements.content.value.trim(),files:await prepFiles(f.elements.files.files)});closeCourseDialog();}catch(err){alert(`添加失败：${err.message}`)}});
$('#importCourseBtn').onclick=()=>$('#courseImportInput').click();$('#courseImportInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{addCourseItem({title:file.name.replace(/\.[^.]+$/,''),content:await file.text(),files:await prepFiles([file])});}catch{alert('该文档无法读取，或文件超过 2MB。请使用 TXT、Markdown 或纯文本文件。')}finally{e.target.value=''}};
$('#saveNotesBtn').onclick=()=>{const s=active();s.nextLesson=$('#nextLesson').value;s.focusContent=$('#focusContent').value;save();const b=$('#saveNotesBtn');b.textContent='已保存';setTimeout(()=>b.textContent='保存更改',1400)};
$('#deleteStudentBtn').onclick=()=>{const s=active();if(confirm(`确定删除「${s.name}」的所有档案吗？`)){state.students=state.students.filter(x=>x.id!==s.id);state.activeId=state.students[0]?.id||null;save();render();}};

function setDataMessage(message, error=false){const el=$('#dataMessage');el.textContent=message;el.style.color=error?'#ad5144':''}
function renderSyncStatus(){const configured=!!cloud.userEmail;$('#syncStatus').textContent='数据中心';$('#syncDot').className='sidebar-auth-dot'+(configured?' online':'');$('#sidebarStorageText').textContent=configured?`已登录：${cloud.userEmail}`:'数据仅保存于此浏览器';$('#cloudSummary').textContent=configured?`已登录 ${cloud.userEmail} · ${cloud.auto?'自动同步已开启':'手动同步'}`:'尚未登录同步账号';$('#openCloudSettings').textContent=configured?'账号设置':'登录账号';$('#logoutFromDataBtn').hidden=!configured;}
async function startRealtime(userId){if(!supabaseClient)return;if(realtimeChannel)await supabaseClient.removeChannel(realtimeChannel);realtimeChannel=supabaseClient.channel(`tutor-profile-${userId}`).on('postgres_changes',{event:'*',schema:'public',table:'tutor_profiles',filter:`user_id=eq.${userId}`},payload=>{const incoming=payload.new?.data;if(incoming?.students){state=incoming;save(false);render();setDataMessage('已接收其他设备的最新档案。')}}).subscribe()}
async function syncCloud(direction, quiet=false){
  if(!supabaseClient){if(!quiet)setDataMessage('同步组件未能加载，请检查网络后刷新页面。',true);return}
  const {data:{user}}=await supabaseClient.auth.getUser();
  if(!user){if(!quiet){if(!$('#cloudDialog').open)$('#cloudDialog').showModal();setAuthMessage('请先登录或注册同步账号。',true)}return}
  $('#syncDot').className='sidebar-auth-dot busy';$('#syncStatus').textContent='同步中';
  try{if(direction==='push'){const {error}=await supabaseClient.from('tutor_profiles').upsert({user_id:user.id,data:state,updated_at:new Date().toISOString()});if(error)throw error}else{const {data,error}=await supabaseClient.from('tutor_profiles').select('data').eq('user_id',user.id).maybeSingle();if(error)throw error;if(data?.data?.students){state=data.data;save(false);render()}}cloud.lastSync=new Date().toISOString();cloud.userEmail=user.email||'';localStorage.setItem(cloudKey,JSON.stringify(cloud));renderSyncStatus();if(!quiet){setDataMessage(direction==='push'?'已上传至云端。':'已拉取云端最新档案。')}}catch(err){renderSyncStatus();if(!quiet){if(!$('#dataDialog').open)$('#dataDialog').showModal();setDataMessage(`同步失败：${err.message}。请确认已执行 Supabase 数据表配置。`,true)}}
}
function downloadFile(content,name,type,message){const blob=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);setDataMessage(message)}
function studentMarkdown(s,plain=false){const h=plain?'':'# ';const bullet=plain?'':'- ';const course=(s.courseProgress||[]).map(x=>`${bullet}${x.date}：${x.title||x.text}${x.content?`（${x.content}）`:''}`).join('\n')||`${bullet}暂无`;const scores=(s.scores||[]).map(x=>plain?`${x.date}｜${x.label}｜${x.score}`:`| ${x.date} | ${x.label} | ${x.score} |`).join('\n')||`${bullet}暂无`;const custom=(s.custom||[]).map(x=>`${bullet}${x.key}：${x.value}`).join('\n')||`${bullet}暂无`;return `${plain?'学生：':'## '}${s.name}\n${bullet}就读学校：${s.school||''}\n${bullet}目标学校：${s.targetSchool||''}\n${bullet}目前分数：${s.currentScore??''}\n${bullet}目标分数：${s.targetScore??''}\n\n${plain?'考试成绩：':'### 考试成绩'}\n${plain?'日期｜考试｜分数\n':''}${scores}\n\n${plain?'课程进度：':'### 课程进度'}\n${course}\n\n${plain?'教学备忘：':'### 教学备忘'}\n${bullet}下节课要讲的内容：${s.nextLesson||''}\n${bullet}着重要听的内容：${s.focusContent||''}\n\n${plain?'其他信息：':'### 其他信息'}\n${custom}`}
function markdownBackup(plain=false){const header=plain?`知行家教学生档案\n导出日期：${new Date().toLocaleString('zh-CN')}`:`# 知行家教学生档案\n\n> 导出日期：${new Date().toLocaleString('zh-CN')}`;return `${header}\n\n${state.students.map(s=>studentMarkdown(s,plain)).join('\n\n---\n\n')}\n`}
function downloadBackup(){downloadFile(JSON.stringify({version:1,exportedAt:new Date().toISOString(),...state},null,2),`知行家教档案-${today()}.json`,'application/json','JSON 备份文件已开始下载。')}
function textValue(line,label){const m=line.match(new RegExp(`^(?:[-*]\\s*)?${label}[：:]\\s*(.*)$`));return m?m[1].trim():''}
function parseTextBackup(text){const blocks=text.split(/(?:^|\n)(?:##\s+|学生[：:])/).slice(1);const students=blocks.map(block=>{const lines=block.split('\n').map(x=>x.trim()).filter(Boolean);const s={id:crypto.randomUUID(),name:(lines.shift()||'未命名学生').replace(/^#+\s*/,'').trim(),school:'',targetSchool:'',currentScore:null,targetScore:null,scores:[],custom:[],courseProgress:[],nextLesson:'',focusContent:''};let section='profile';for(const line of lines){if(/^###\s*考试成绩|^考试成绩[：:]?$/.test(line)){section='scores';continue}if(/^###\s*课程进度|^课程进度[：:]?$/.test(line)){section='course';continue}if(/^###\s*教学备忘|^教学备忘[：:]?$/.test(line)){section='notes';continue}if(/^###\s*其他信息|^其他信息[：:]?$/.test(line)){section='custom';continue}const clean=line.replace(/^[-*]\s*/,'');if(section==='scores'&&clean.includes('｜')){const [date,label,score]=clean.split('｜').map(x=>x.trim());if(date&&label&&!Number.isNaN(Number(score)))s.scores.push({date,label,score:+score});continue}if(section==='scores'&&/^\|/.test(clean)){const cells=clean.split('|').map(x=>x.trim()).filter(Boolean);if(cells.length>=3&&!Number.isNaN(Number(cells[2])))s.scores.push({date:cells[0],label:cells[1],score:+cells[2]});continue}if(section==='course'&&clean!=='暂无'){const m=clean.match(/^(.+?)[：:]\s*(.+)$/);s.courseProgress.push(m?{date:m[1],text:m[2]}:{date:'',text:clean});continue}const pairs=[['就读学校','school'],['目标学校','targetSchool'],['目前分数','currentScore'],['目标分数','targetScore'],['下节课要讲的内容','nextLesson'],['着重要听的内容','focusContent']];let matched=false;for(const [label,key] of pairs){const value=textValue(clean,label);if(value!==''||clean.startsWith(label+'：')||clean.startsWith(label+':')){s[key]=(key.includes('Score')?Number(value)||null:value);matched=true;break}}if(section==='custom'&&!matched&&clean!=='暂无'){const m=clean.match(/^(.+?)[：:]\s*(.+)$/);if(m)s.custom.push({key:m[1],value:m[2]})}}return s}).filter(s=>s.name&&s.name!=='未命名学生');if(!students.length)throw new Error('未识别到学生档案；请使用本应用导出的 Markdown 或文字文件');return {students,activeId:students[0].id}}
function openDataCenter(){$('#dataDialog').showModal();renderSyncStatus();setDataMessage('所有档案优先保存在本机浏览器中。')}
$('#sidebarAuthButton').onclick=openDataCenter;
$('#exportBtn').onclick=downloadBackup;
$('#exportMarkdownBtn').onclick=()=>downloadFile(markdownBackup(),`知行家教档案-${today()}.md`,'text/markdown;charset=utf-8','Markdown 档案已开始下载。');
$('#exportTextBtn').onclick=()=>downloadFile(markdownBackup(true),`知行家教档案-${today()}.txt`,'text/plain;charset=utf-8','文字档案已开始下载。');
$('#importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const text=await file.text();let next;try{next=JSON.parse(text)}catch{next=parseTextBackup(text)}if(!Array.isArray(next.students))throw new Error('文件中没有有效学生档案');if(!confirm(`将导入 ${next.students.length} 位学生并覆盖当前本地档案，是否继续？`))return;state={students:next.students,activeId:next.activeId||next.students[0]?.id||null,updatedAt:new Date().toISOString()};save();render();setDataMessage(`已导入 ${state.students.length} 位学生的档案。`)}catch(err){setDataMessage(`导入失败：${err.message}`,true)}finally{e.target.value=''}});
function setAuthMessage(message,error=false){const el=$('#authMessage');el.textContent=message;el.style.color=error?'#b54d42':''}
function openAuth(){const f=$('#cloudForm');f.reset();f.elements.auto.checked=cloud.auto!==false;$('#logoutBtn').hidden=!cloud.userEmail;setAuthMessage(cloud.userEmail?`当前已登录：${cloud.userEmail}`:'');$('#cloudDialog').showModal()}
function confirmCloseAuth(){if(confirm('确定关闭登录窗口吗？未登录不会影响本地档案。'))$('#cloudDialog').close('cancel')}
$('#openCloudSettings').onclick=openAuth;
$('#emptyLoginButton').onclick=openAuth;
$('#closeCloudDialog').onclick=confirmCloseAuth;$('#cancelCloudDialog').onclick=confirmCloseAuth;
$('#cloudDialog').addEventListener('cancel',e=>{e.preventDefault();confirmCloseAuth()});
async function logout(){if(!confirm('确定退出当前账号吗？这台设备上的学生档案缓存会被清除，但云端档案不会删除。'))return;const {error}=await supabaseClient.auth.signOut();if(error){setAuthMessage(`退出失败：${error.message}`,true);return}if(realtimeChannel)await supabaseClient.removeChannel(realtimeChannel);realtimeChannel=null;state={students:[],activeId:null};localStorage.removeItem(storeKey);cloud={auto:cloud.auto,lastSync:null,userEmail:''};localStorage.setItem(cloudKey,JSON.stringify(cloud));$('#cloudDialog').close();if($('#dataDialog').open)$('#dataDialog').close();render();}
$('#logoutBtn').onclick=logout;$('#logoutFromDataBtn').onclick=logout;
$('#authModeBtn').onclick=()=>{authRegister=!authRegister;$('#authTitle').textContent=authRegister?'注册同步账号':'登录云端';$('#authSubmitBtn').textContent=authRegister?'注册并继续':'登录并同步';$('#authModeBtn').textContent=authRegister?'已有账号？登录':'没有账号？注册';$('#cloudForm').elements.password.autocomplete=authRegister?'new-password':'current-password';setAuthMessage('')};
$('#resendConfirmBtn').onclick=async()=>{const email=$('#cloudForm').elements.email.value.trim();if(!email){setAuthMessage('请先填写注册时使用的邮箱地址。',true);return}try{const {error}=await supabaseClient.auth.resend({type:'signup',email,options:{emailRedirectTo:appRedirectUrl}});if(error)throw error;setAuthMessage('确认邮件已重新发送，请同时检查垃圾邮件箱。')}catch(err){setAuthMessage(`发送失败：${err.message}`,true)}};
$('#cloudForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const f=e.currentTarget,email=f.elements.email.value.trim(),password=f.elements.password.value;try{if(authRegister){const {data,error}=await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:appRedirectUrl}});if(error)throw error;if(!data.session){setAuthMessage('注册成功，请到邮箱确认后再登录。');return}}else{const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error}const {data:{user}}=await supabaseClient.auth.getUser();cloud={...cloud,auto:f.elements.auto.checked,userEmail:email};localStorage.setItem(cloudKey,JSON.stringify(cloud));if(user)await startRealtime(user.id);await syncCloud('pull',true);await syncCloud('push',true);$('#cloudDialog').close();render();if(!$('#dataDialog').open)$('#dataDialog').showModal();setDataMessage('登录成功，已开启自动同步。')}catch(err){setAuthMessage(`操作失败：${err.message}`,true)}});
$('#pushBtn').onclick=()=>syncCloud('push');$('#pullBtn').onclick=()=>syncCloud('pull');
async function restoreSession(){if(!supabaseClient)return;const {data:{user}}=await supabaseClient.auth.getUser();if(user){cloud.userEmail=user.email||'';localStorage.setItem(cloudKey,JSON.stringify(cloud));await startRealtime(user.id);render();syncCloud('pull',true)}}
window.addEventListener('resize',()=>{if(active())drawChart((active().scores||[]).slice().sort((a,b)=>a.date.localeCompare(b.date)))});render();restoreSession();
