const storeKey = 'zhixing-tutor-students-v1';
let state = window.Zhixing.Model.ensureIds(JSON.parse(localStorage.getItem(storeKey) || '{"students":[],"activeId":null}'));
const $ = s => document.querySelector(s);
const cloudKey = 'zhixing-tutor-cloud-v1';
const supabaseUrl='https://nnnxsjqbklnykshqgntt.supabase.co',supabaseKey='sb_publishable_SaQQauIlc5EJqG7IhKWQFw_mYctgZiR',storageBucket='tutor-files',storageEndpoint=`${supabaseUrl}/storage/v1/upload/resumable`;
const supabaseClient = window.supabase?.createClient(supabaseUrl,supabaseKey);
window.Zhixing.Files.configure({client:supabaseClient,bucket:storageBucket,endpoint:storageEndpoint,onStatus:message=>{setDataMessage(message);renderSyncStatus()}});
let cloud = JSON.parse(localStorage.getItem(cloudKey) || '{"auto":true,"lastSync":null,"userEmail":""}');
let authRegister = false;
let autoSyncTimer;
let realtimeChannel;
let syncEngine='local';
let pendingPrepFolderFiles=[];
let pendingCourseFolderFiles=[];
const save = (scheduleCloud=true) => { state=window.Zhixing.Model.ensureIds(state);state.updatedAt = new Date().toISOString(); localStorage.setItem(storeKey, JSON.stringify(state));window.Zhixing.Database.persist(state,scheduleCloud).then(()=>{if(scheduleCloud&&cloud.auto&&cloud.userEmail){if(syncEngine==='v2')window.Zhixing.Sync.schedule();else{clearTimeout(autoSyncTimer);autoSyncTimer=setTimeout(()=>syncCloud('push',true),1200)}}renderSyncStatus()}).catch(err=>setDataMessage(`本地保存失败：${err.message}`,true)); };
const esc = v => String(v || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const active = () => state.students.find(s => s.id === state.activeId);
const initials = name => (name || '?').trim().slice(0,2);
const today = () => new Date().toISOString().slice(0,10);
const appRedirectUrl = new URL('./', window.location.href).href;
const snapshotForm=form=>JSON.stringify([...new FormData(form).entries()].filter(([,value])=>typeof value==='string'));
const markClean=form=>form.dataset.cleanSnapshot=snapshotForm(form);
const isDirty=form=>snapshotForm(form)!==(form.dataset.cleanSnapshot||'[]')||[...form.querySelectorAll('input[type=file]')].some(input=>input.files.length);
function ask(message,{title='请确认',danger=false}={}){return new Promise(resolve=>{const dialog=$('#confirmDialog');$('#confirmTitle').textContent=title;$('#confirmMessage').textContent=message;$('#confirmAccept').className=danger?'primary-btn danger-confirm':'primary-btn';dialog.returnValue='cancel';dialog.onclose=()=>resolve(dialog.returnValue==='confirm');dialog.showModal()})}
async function closeFormDialog(dialog,form,message){if(isDirty(form)&&!await ask(message))return;dialog.close('cancel')}
function downloadStoredFile(file){return async()=>{try{let href=file.data;if(file.path){const {data,error}=await supabaseClient.storage.from(storageBucket).createSignedUrl(file.path,300,{download:file.name});if(error)throw error;href=data.signedUrl}if(!href)throw new Error('这是旧版本记录的附件名称，请重新添加文件');const link=document.createElement('a');link.href=href;link.download=file.name;link.click();}catch(err){alert(`下载失败：${err.message}`)}}}
function fileTypeLabel(file){if(file.pending)return '待上传';const ext=(file.name.split('.').pop()||'').toUpperCase();return ['PDF','DOC','DOCX','PPT','PPTX','XLS','XLSX','TXT','MD','PNG','JPG','JPEG','WEBP'].includes(ext)?(ext==='JPEG'?'JPG':ext||'文件'):'文件'}function attachmentMarkup(file,itemIndex,fileIndex,kind){const isCourse=kind==='course',name=file.relativePath||file.name;return `<span class="attachment${file.pending?' pending':''}"><button class="prep-file ${isCourse?'course-file':''}" data-i="${itemIndex}" data-file="${fileIndex}" type="button" ${file.pending?'disabled':''} title="${file.pending?'联网后自动上传':`下载 ${esc(name)}`}"><svg class="attachment-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2.8h8l4 4v14.4H6zM14 2.8v4.5h4"/></svg><span class="attachment-name">${esc(name)}</span><small>${fileTypeLabel(file)}</small></button><button class="remove-attachment ${isCourse?'course-attachment':'prep-attachment'}" data-i="${itemIndex}" data-file="${fileIndex}" type="button" aria-label="删除文件 ${esc(name)}">×</button></span>`}
function isTextFile(file){return /^text\//.test(file.type)||/\.(txt|md|markdown)$/i.test(file.name)}

function renderList(){
  $('#studentCount').textContent = state.students.length;
  $('#studentList').innerHTML = state.students.map(s => `<button class="student-item ${s.id===state.activeId?'active':''}" data-id="${s.id}"><span class="avatar">${esc(initials(s.name))}</span><span>${esc(s.name)}<small>${esc(s.school || '未填写学校')}</small></span></button>`).join('');
  document.querySelectorAll('.student-item').forEach(b=>b.onclick=()=>{state.activeId=b.dataset.id;save();render();});
}
function render(){
  renderSyncStatus();
  const signedIn=!!cloud.userEmail,landing=!signedIn&&!state.students.length;
  document.body.classList.toggle('logged-out',landing);
  if(landing){$('#emptyState').hidden=false;$('#studentView').hidden=true;return}
  if(!active()&&state.students.length){state.activeId=state.students[0].id;save(false)}
  renderList(); const s=active(); $('#emptyState').hidden=!!s;$('#emptyLoginButton').hidden=signedIn; $('#studentView').hidden=!s; if(!s)return;
  $('#studentNameTitle').textContent=s.name; $('#studentMeta').textContent=`${s.school || '未填写学校'} · 学生档案`;
  $('#schoolText').textContent=s.school || '待补充'; $('#targetSchoolText').textContent=s.targetSchool || '待补充';
  $('#currentScore').textContent=s.currentScore ?? '—'; $('#targetScore').textContent=s.targetScore ?? '—';
  const numericScore=value=>/^\s*-?\d+(?:\.\d+)?\s*$/.test(String(value??''))?Number(value):null,currentNumber=numericScore(s.currentScore),targetNumber=numericScore(s.targetScore);const scoreRatio=targetNumber!==null&&currentNumber!==null&&targetNumber!==0?Math.max(0,Math.min(100,Math.round(currentNumber/targetNumber*100))):0; $('#scoreRing').style.setProperty('--p',scoreRatio+'%');
  $('#goalHint').textContent=targetNumber!==null&&currentNumber!==null?`距离目标还差 ${Math.max(0,targetNumber-currentNumber)} 分`:'已使用自由格式记录分数目标';
  $('#nextLesson').value=s.nextLesson||''; $('#focusContent').value=s.focusContent||'';
  $('#customFields').innerHTML=(s.custom||[]).map((f,i)=>`<div class="custom-field"><span>${esc(f.key)}</span><strong>${esc(f.value)}</strong><button class="remove-custom" data-i="${i}" title="删除">×</button></div>`).join('')||'<div class="no-data" style="position:static;display:block;text-align:left">添加需要长期记录的信息</div>';
  document.querySelectorAll('.remove-custom').forEach(b=>b.onclick=async()=>{if(!await ask('删除这条自定义信息吗？',{title:'删除信息',danger:true}))return;s.custom.splice(+b.dataset.i,1);save();render();});
  const scores=(s.scores||[]).slice().sort((a,b)=>a.date.localeCompare(b.date));
  $('#scoreHistory').innerHTML=scores.map((x,i)=>`<span class="score-chip">${esc(x.label)} <b>${x.score}</b> <button class="remove-score" data-i="${i}" title="删除">×</button></span>`).join('');
  document.querySelectorAll('.remove-score').forEach(b=>b.onclick=async()=>{if(!await ask('删除这条考试成绩吗？',{title:'删除成绩',danger:true}))return;const original=scores[+b.dataset.i];s.scores.splice(s.scores.indexOf(original),1);save();render();});
  const course=(s.courseProgress||[]); $('#courseList').innerHTML=course.map((item,i)=>`<article class="prep-item"><div class="prep-item-head"><div><h3>${esc(item.title||item.text)}</h3><time>${esc(item.date)}</time></div><div class="item-actions"><button class="edit-course" data-i="${i}" type="button">编辑</button><button class="remove-course" data-i="${i}" type="button" aria-label="删除该条进度">×</button></div></div>${item.content?`<p>${esc(item.content).replace(/\n/g,'<br>')}</p>`:''}${item.files?.length?`<div class="prep-files">${item.files.map((file,j)=>attachmentMarkup(file,i,j,'course')).join('')}</div>`:''}</article>`).join('')||'<p class="course-empty">还没有课程进度。点击“添加进度”开始记录。</p>';
  document.querySelectorAll('.remove-course').forEach(b=>b.onclick=async()=>{if(!await ask('删除这条课程进度及其附件吗？',{title:'删除课程进度',danger:true}))return;course.splice(+b.dataset.i,1);s.courseProgress=course;save();render();});
  document.querySelectorAll('.edit-course').forEach(b=>b.onclick=()=>openCourseEditor(+b.dataset.i));
  document.querySelectorAll('.course-file').forEach(b=>b.onclick=downloadStoredFile(course[+b.dataset.i].files[+b.dataset.file]));
  document.querySelectorAll('.course-attachment').forEach(b=>b.onclick=()=>{course[+b.dataset.i].files.splice(+b.dataset.file,1);save();render();});
  const preparations=s.preparations||[];$('#prepList').innerHTML=preparations.map((item,i)=>`<article class="prep-item"><div class="prep-item-head"><div><h3>${esc(item.title)}</h3><time>${esc(item.date)}</time></div><div class="item-actions"><button class="edit-prep" data-i="${i}" type="button">编辑</button><button class="remove-prep" data-i="${i}" type="button" aria-label="删除这次备课">×</button></div></div>${item.content?`<p>${esc(item.content).replace(/\n/g,'<br>')}</p>`:''}${item.files?.length?`<div class="prep-files">${item.files.map((file,j)=>attachmentMarkup(file,i,j,'prep')).join('')}</div>`:''}</article>`).join('')||'<p class="course-empty">还没有备课条目。点击“添加备课”开始记录。</p>';
  document.querySelectorAll('.remove-prep').forEach(b=>b.onclick=async()=>{if(!await ask('删除这次备课及其附件吗？',{title:'删除备课',danger:true}))return;preparations.splice(+b.dataset.i,1);s.preparations=preparations;save();render();});
  document.querySelectorAll('.edit-prep').forEach(b=>b.onclick=()=>openPrepEditor(+b.dataset.i));
  document.querySelectorAll('.prep-file:not(.course-file)').forEach(b=>b.onclick=downloadStoredFile(preparations[+b.dataset.i].files[+b.dataset.file]));
  document.querySelectorAll('.prep-attachment').forEach(b=>b.onclick=()=>{preparations[+b.dataset.i].files.splice(+b.dataset.file,1);save();render();});
  $('#noScores').style.display=scores.length?'none':'grid'; drawChart(scores);
}
function drawChart(data){
  const canvas=$('#scoreChart'), wrap=canvas.parentElement, dpr=devicePixelRatio||1; const w=wrap.clientWidth,h=wrap.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);if(!data.length)return;
  const p={l:38,r:16,t:20,b:35}, vals=data.map(x=>Number(x.score));let min=Math.floor((Math.min(...vals)-5)/10)*10,max=Math.ceil((Math.max(...vals)+5)/10)*10;if(min===max){min-=10;max+=10};const X=i=>p.l+i*((w-p.l-p.r)/Math.max(1,data.length-1)),Y=v=>p.t+(max-v)/(max-min)*(h-p.t-p.b);
  c.font='11px DM Mono, monospace';c.textAlign='right';c.fillStyle='#8195aa';c.strokeStyle='#e5eef7';c.lineWidth=1;for(let i=0;i<4;i++){const val=min+(max-min)*i/3,y=Y(val);c.beginPath();c.moveTo(p.l,y);c.lineTo(w-p.r,y);c.stroke();c.fillText(Math.round(val),p.l-8,y+4)}
  const grad=c.createLinearGradient(0,p.t,0,h-p.b);grad.addColorStop(0,'rgba(31,111,235,.24)');grad.addColorStop(1,'rgba(31,111,235,0)');c.beginPath();data.forEach((x,i)=>i?c.lineTo(X(i),Y(x.score)):c.moveTo(X(i),Y(x.score)));c.lineTo(X(data.length-1),h-p.b);c.lineTo(X(0),h-p.b);c.closePath();c.fillStyle=grad;c.fill();
  c.beginPath();data.forEach((x,i)=>i?c.lineTo(X(i),Y(x.score)):c.moveTo(X(i),Y(x.score)));c.strokeStyle='#1f6feb';c.lineWidth=3;c.stroke();c.textAlign='center';data.forEach((x,i)=>{const px=X(i),py=Y(x.score);c.beginPath();c.arc(px,py,4,0,Math.PI*2);c.fillStyle='#b9dcff';c.fill();c.strokeStyle='#175da8';c.lineWidth=2;c.stroke();c.fillStyle='#647f9c';c.font='10px Manrope';c.fillText(x.label.length>6?x.label.slice(0,6)+'…':x.label,px,h-13);});
}
function openStudent(edit=false){const s=active();const f=$('#studentForm');f.reset();$('#studentDialogTitle').textContent=edit?'编辑学生资料':'添加学生';f.dataset.edit=edit?'1':'';if(edit&&s)Object.entries({name:s.name,school:s.school,targetSchool:s.targetSchool,currentScore:s.currentScore,targetScore:s.targetScore}).forEach(([k,v])=>f.elements[k].value=v??'');markClean(f);$('#studentDialog').showModal();}
$('#openStudentDialog').onclick=()=>openStudent();$('#emptyAddButton').onclick=()=>openStudent();$('#editStudentBtn').onclick=()=>openStudent(true);
function confirmCloseStudent(){return closeFormDialog($('#studentDialog'),$('#studentForm'),'确定关闭吗？尚未保存的填写内容将不会保留。')}
$('#closeStudentDialog').onclick=confirmCloseStudent;$('#cancelStudentDialog').onclick=confirmCloseStudent;
$('#studentDialog').addEventListener('cancel',e=>{e.preventDefault();confirmCloseStudent()});
$('#studentForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const f=e.currentTarget,d=Object.fromEntries(new FormData(f));const n={...d,currentScore:d.currentScore.trim()||null,targetScore:d.targetScore.trim()||null};if(f.dataset.edit){Object.assign(active(),n)}else{const s={id:crypto.randomUUID(),...n,scores:[],custom:[],courseProgress:[],preparations:[],nextLesson:'',focusContent:''};state.students.push(s);state.activeId=s.id}save();render();});
function openScore(){$('#scoreForm').reset();$('#scoreForm').elements.date.value=today();markClean($('#scoreForm'));$('#scoreDialog').showModal()}$('#addScoreBtn').onclick=openScore;$('#noScoreButton').onclick=openScore;
$('#scoreForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const d=Object.fromEntries(new FormData(e.currentTarget)),score=Number(d.score.trim());if(!Number.isFinite(score)){e.preventDefault();alert('请输入有效的数字分数，例如 86 或 86.5。');return}active().scores.push({...d,score});active().currentScore=String(score);save();render();});
function closeCustomDialog(){return closeFormDialog($('#customDialog'),$('#customForm'),'放弃尚未保存的自定义信息吗？')}$('#addCustomBtn').onclick=()=>{const f=$('#customForm');f.reset();markClean(f);$('#customDialog').showModal()};$('#closeCustomDialog').onclick=closeCustomDialog;$('#cancelCustomDialog').onclick=closeCustomDialog;$('#customForm').addEventListener('submit',e=>{const d=Object.fromEntries(new FormData(e.currentTarget));active().custom.push(d);save();render();});
function closePrepDialog(force=false){if(force)$('#prepDialog').close();else return closeFormDialog($('#prepDialog'),$('#prepForm'),'放弃尚未保存的备课内容吗？')}async function uploadFiles(files,section,recordId,status){const list=[...files];if(!list.length)return[];const student=active();if(!student)throw new Error('未找到当前学生档案');return window.Zhixing.Files.prepare(list,section,recordId,student.id,status)}function addPreparation({id=crypto.randomUUID(),title,content='',files=[]}){const s=active();s.preparations=s.preparations||[];s.preparations.unshift({id,title,content,files,date:new Date().toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})});save();render();}function openPrepEditor(index){const item=active().preparations[index],f=$('#prepForm');f.reset();pendingPrepFolderFiles=[];f.dataset.editIndex=String(index);f.elements.title.value=item.title;f.elements.content.value=item.content||'';markClean(f);$('#prepDialog h2').textContent='编辑备课';$('#prepFilesHint').textContent=item.files?.length?`已有 ${item.files.length} 个附件；新选择的文件会追加`:'可添加讲义、图片、PDF 等文件';$('#prepDialog').showModal()}
$('#addPrepBtn').onclick=()=>{const f=$('#prepForm');f.reset();pendingPrepFolderFiles=[];delete f.dataset.editIndex;markClean(f);$('#prepDialog h2').textContent='新增备课';$('#prepFilesHint').textContent='可添加讲义、图片、PDF 等文件';$('#prepDialog').showModal()};$('#closePrepDialog').onclick=()=>closePrepDialog();$('#cancelPrepDialog').onclick=()=>closePrepDialog();
$('#prepForm').elements.files.onchange=e=>{$('#prepFilesHint').textContent=e.target.files.length?`已选择 ${e.target.files.length} 个文件（将上传至私有云端）`:'可添加讲义、图片、PDF 等文件'};
$('#prepForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{const editIndex=f.dataset.editIndex,item=editIndex!==undefined?active().preparations[+editIndex]:null,recordId=item?.id||crypto.randomUUID(),selected=[...f.elements.files.files,...pendingPrepFolderFiles],addedFiles=await uploadFiles(selected,'preparations',recordId,message=>$('#prepFilesHint').textContent=message);if(item){Object.assign(item,{title:f.elements.title.value.trim(),content:f.elements.content.value.trim(),files:[...(item.files||[]),...addedFiles]});save();render();}else addPreparation({id:recordId,title:f.elements.title.value.trim(),content:f.elements.content.value.trim(),files:addedFiles});pendingPrepFolderFiles=[];delete f.dataset.editIndex;closePrepDialog(true);}catch(err){alert(`保存失败：${err.message}`)}});
$('#prepFolderPickerBtn').onclick=()=>$('#prepFolderInput').click();$('#prepFolderInput').onchange=e=>{pendingPrepFolderFiles=[...e.target.files];const folderName=pendingPrepFolderFiles[0]?.webkitRelativePath?.split('/')[0]||'文件夹';$('#prepFilesHint').textContent=pendingPrepFolderFiles.length?`已选择文件夹「${folderName}」，共 ${pendingPrepFolderFiles.length} 个文件`:'可添加讲义、图片、PDF 等文件';e.target.value=''};
function closeCourseDialog(force=false){if(force)$('#courseDialog').close();else return closeFormDialog($('#courseDialog'),$('#courseItemForm'),'放弃尚未保存的课程进度吗？')}function addCourseItem({id=crypto.randomUUID(),title,content='',files=[]}){const s=active();s.courseProgress=s.courseProgress||[];s.courseProgress.unshift({id,title,content,files,date:new Date().toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})});save();render();}function openCourseEditor(index){const item=active().courseProgress[index],f=$('#courseItemForm');f.reset();pendingCourseFolderFiles=[];f.dataset.editIndex=String(index);f.elements.title.value=item.title||item.text||'';f.elements.content.value=item.content||'';markClean(f);$('#courseDialog h2').textContent='编辑进度';$('#courseFilesHint').textContent=item.files?.length?`已有 ${item.files.length} 个附件；新选择的文件会追加`:'可添加作业、讲义、图片、PDF 等文件';$('#courseDialog').showModal()}
$('#addCourseBtn').onclick=()=>{const f=$('#courseItemForm');f.reset();delete f.dataset.editIndex;pendingCourseFolderFiles=[];markClean(f);$('#courseDialog h2').textContent='新增进度';$('#courseFilesHint').textContent='可添加作业、讲义、图片、PDF 等文件';$('#courseDialog').showModal()};$('#closeCourseDialog').onclick=()=>closeCourseDialog();$('#cancelCourseDialog').onclick=()=>closeCourseDialog();
$('#courseItemForm').elements.files.onchange=e=>{$('#courseFilesHint').textContent=e.target.files.length?`已选择 ${e.target.files.length} 个文件（将上传至私有云端）`:'可添加作业、讲义、图片、PDF 等文件'};
$('#courseItemForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{const editIndex=f.dataset.editIndex,item=editIndex!==undefined?active().courseProgress[+editIndex]:null,id=item?.id||crypto.randomUUID(),selected=[...f.elements.files.files,...pendingCourseFolderFiles],files=await uploadFiles(selected,'course-progress',id,message=>$('#courseFilesHint').textContent=message);if(item){Object.assign(item,{title:f.elements.title.value.trim(),content:f.elements.content.value.trim(),files:[...(item.files||[]),...files]});save();render()}else addCourseItem({id,title:f.elements.title.value.trim(),content:f.elements.content.value.trim(),files});pendingCourseFolderFiles=[];delete f.dataset.editIndex;closeCourseDialog(true);}catch(err){alert(`保存失败：${err.message}`)}});
$('#courseFolderPickerBtn').onclick=()=>$('#courseFolderInput').click();$('#courseFolderInput').onchange=e=>{pendingCourseFolderFiles=[...e.target.files];const folderName=pendingCourseFolderFiles[0]?.webkitRelativePath?.split('/')[0]||'文件夹';$('#courseFilesHint').textContent=pendingCourseFolderFiles.length?`已选择文件夹「${folderName}」，共 ${pendingCourseFolderFiles.length} 个文件`:'可添加作业、讲义、图片、PDF 等文件';e.target.value=''};
$('#saveNotesBtn').onclick=()=>{const s=active();s.nextLesson=$('#nextLesson').value;s.focusContent=$('#focusContent').value;save();const b=$('#saveNotesBtn');b.textContent='已保存';setTimeout(()=>b.textContent='保存更改',1400)};
$('#deleteStudentBtn').onclick=async()=>{const s=active();if(!await ask(`确定删除「${s.name}」的全部档案与附件吗？`,{title:'删除学生档案',danger:true}))return;state.students=state.students.filter(x=>x.id!==s.id);state.activeId=state.students[0]?.id||null;save();render()};

function setDataMessage(message, error=false){const el=$('#dataMessage');el.textContent=message;el.style.color=error?'#ad5144':''}
async function renderConflicts(){const conflicts=await window.Zhixing.Database.all('conflicts'),section=$('#conflictSection'),list=$('#conflictList');section.hidden=!conflicts.length;list.innerHTML=conflicts.map(c=>`<article class="conflict-item"><strong>${esc(c.entity)} · ${esc(c.local?.data?.title||c.local?.data?.name||c.local?.data?.label||c.id)}</strong><span>本机与云端都已修改</span><div><button type="button" class="outline-btn conflict-choice" data-key="${esc(c.key)}" data-choice="cloud">采用云端版</button><button type="button" class="primary-btn conflict-choice" data-key="${esc(c.key)}" data-choice="local">保留本机版</button></div></article>`).join('');document.querySelectorAll('.conflict-choice').forEach(button=>button.onclick=async()=>{await window.Zhixing.Sync.resolve(button.dataset.key,button.dataset.choice);state=await window.Zhixing.Database.state();localStorage.setItem(storeKey,JSON.stringify(state));render();renderSyncStatus();renderConflicts()})}
async function renderUploadQueue(){const queue=(await window.Zhixing.Database.all('outbox')).filter(item=>item.entity==='attachments'&&item.data.localBlobKey),el=$('#uploadQueue');el.hidden=!queue.length;el.innerHTML=queue.map(item=>`<div class="upload-item"><span>${esc(item.data.name)} · ${item.attempts?`重试 ${item.attempts} 次`:'等待上传'}</span><button type="button" class="text-btn cancel-upload" data-key="${esc(item.key)}">取消</button></div>`).join('');document.querySelectorAll('.cancel-upload').forEach(button=>button.onclick=async()=>{await window.Zhixing.Database.discardLocalRecord(button.dataset.key);state=await window.Zhixing.Database.state();localStorage.setItem(storeKey,JSON.stringify(state));render();renderSyncStatus()})}
async function renderSyncStatus(){const configured=!!cloud.userEmail,stats=await window.Zhixing.Database.stats().catch(()=>({pending:0,cleanup:0,conflicts:0,failed:0}));$('#syncStatus').textContent='数据中心';$('#syncDot').className='sidebar-auth-dot'+(configured?(navigator.onLine?' online':' busy'):'');$('#sidebarStorageText').textContent=configured?`已登录：${cloud.userEmail}`:'数据仅保存于此浏览器';$('#cloudSummary').textContent=configured?`已登录 ${cloud.userEmail} · ${cloud.auto?'自动同步已开启':'手动同步'}`:'尚未登录同步账号';$('#syncDetail').textContent=navigator.onLine?`待同步 ${stats.pending} · 待清理 ${stats.cleanup} · 冲突 ${stats.conflicts} · 失败 ${stats.failed}`:`当前离线 · 待同步 ${stats.pending} · 待清理 ${stats.cleanup}`;$('#openCloudSettings').textContent=configured?'账号设置':'登录账号';$('#logoutFromDataBtn').hidden=!configured;if($('#dataDialog').open){renderConflicts();renderUploadQueue()}}
async function startLegacyRealtime(userId){syncEngine='legacy';if(realtimeChannel)await supabaseClient.removeChannel(realtimeChannel);realtimeChannel=supabaseClient.channel(`tutor-profile-${userId}`).on('postgres_changes',{event:'*',schema:'public',table:'tutor_profiles',filter:`user_id=eq.${userId}`},payload=>{const incoming=payload.new?.data;if(incoming?.students){state=window.Zhixing.Model.ensureIds(incoming);localStorage.setItem(storeKey,JSON.stringify(state));window.Zhixing.Database.persist(state,false);render();setDataMessage('已通过兼容模式接收云端档案。')}}).subscribe()}
async function startRealtime(){if(!supabaseClient)return;const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;try{await window.Zhixing.Sync.start({client:supabaseClient,onState:next=>{state=next;localStorage.setItem(storeKey,JSON.stringify(state));render();renderSyncStatus()},onStatus:(status,error)=>{if(status==='error'&&error)setDataMessage(`同步失败：${error.message}`,true);renderSyncStatus()}});syncEngine='v2'}catch(error){if(/does not exist|schema cache|Could not find|404/i.test(error.message)){await startLegacyRealtime(user.id);setDataMessage('云端仍使用兼容同步；执行 v2 迁移后会自动升级。')}else throw error}}
async function legacySync(direction,user){if(direction==='push'){const {error}=await supabaseClient.from('tutor_profiles').upsert({user_id:user.id,data:state,updated_at:new Date().toISOString()});if(error)throw error}else{const {data,error}=await supabaseClient.from('tutor_profiles').select('data').eq('user_id',user.id).maybeSingle();if(error)throw error;if(data?.data?.students){state=window.Zhixing.Model.ensureIds(data.data);localStorage.setItem(storeKey,JSON.stringify(state));await window.Zhixing.Database.persist(state,false);render()}}}
async function syncCloud(direction, quiet=false){if(!supabaseClient){if(!quiet)setDataMessage('同步组件未能加载，请检查网络后刷新页面。',true);return}const {data:{user}}=await supabaseClient.auth.getUser();if(!user){if(!quiet){openAuth();setAuthMessage('请先登录或注册同步账号。',true)}return}$('#syncDot').className='sidebar-auth-dot busy';try{if(syncEngine==='v2'){if(direction==='push')await window.Zhixing.Sync.flush();else await window.Zhixing.Sync.pull();await window.Zhixing.Sync.sync()}else await legacySync(direction,user);cloud.lastSync=new Date().toISOString();localStorage.setItem(cloudKey,JSON.stringify(cloud));if(!quiet)setDataMessage(syncEngine==='v2'?(direction==='push'?'本机更改已同步。':'已检查并合并云端记录。'):'已通过兼容模式同步。')}catch(err){if(!quiet)setDataMessage(`同步失败：${err.message}`,true)}finally{renderSyncStatus()}}
function downloadFile(content,name,type,message){const blob=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);setDataMessage(message)}
function fileSummary(files,bullet){return (files||[]).map(f=>`${bullet}附件：${f.relativePath||f.name}${f.path?`｜路径：${f.path}`:''}｜类型：${f.type||'application/octet-stream'}｜大小：${Number(f.size||0)}`).join('\n')}
function studentMarkdown(s,plain=false){const bullet=plain?'':'- ';const course=(s.courseProgress||[]).map(x=>`${bullet}${x.date}：${x.title||x.text}${x.content?`（${x.content}）`:''}\n${fileSummary(x.files,bullet)}`).join('\n')||`${bullet}暂无`;const preparations=(s.preparations||[]).map(x=>`${bullet}${x.date}：${x.title}${x.content?`（${x.content}）`:''}\n${fileSummary(x.files,bullet)}`).join('\n')||`${bullet}暂无`;const scores=(s.scores||[]).map(x=>plain?`${x.date}｜${x.label}｜${x.score}`:`| ${x.date} | ${x.label} | ${x.score} |`).join('\n')||`${bullet}暂无`;const custom=(s.custom||[]).map(x=>`${bullet}${x.key}：${x.value}`).join('\n')||`${bullet}暂无`;return `${plain?'学生：':'## '}${s.name}\n${bullet}就读学校：${s.school||''}\n${bullet}目标学校：${s.targetSchool||''}\n${bullet}目前分数：${s.currentScore??''}\n${bullet}目标分数：${s.targetScore??''}\n\n${plain?'考试成绩：':'### 考试成绩'}\n${plain?'日期｜考试｜分数\n':''}${scores}\n\n${plain?'备课记录：':'### 备课记录'}\n${preparations}\n\n${plain?'课程进度：':'### 课程进度'}\n${course}\n\n${plain?'教学备忘：':'### 教学备忘'}\n${bullet}下节课要讲的内容：${s.nextLesson||''}\n${bullet}着重要听的内容：${s.focusContent||''}\n\n${plain?'其他信息：':'### 其他信息'}\n${custom}`}
function encodedBackup(){const bytes=new TextEncoder().encode(JSON.stringify({version:2,...state}));let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));return btoa(binary)}
function markdownBackup(plain=false){const header=plain?`知行家教学生档案\n导出日期：${new Date().toLocaleString('zh-CN')}`:`# 知行家教学生档案\n\n> 导出日期：${new Date().toLocaleString('zh-CN')}`;return `${header}\n\n${state.students.map(s=>studentMarkdown(s,plain)).join('\n\n---\n\n')}\n\n[[ZHIXING_V2:${encodedBackup()}]]\n`}
function downloadBackup(){downloadFile(JSON.stringify({version:2,exportedAt:new Date().toISOString(),...state},null,2),`知行家教档案-${today()}.json`,'application/json','JSON 备份文件已开始下载。')}
function textValue(line,label){const m=line.match(new RegExp(`^(?:[-*]\\s*)?${label}[：:]\\s*(.*)$`));return m?m[1].trim():''}
function parseTextBackup(text){const encoded=text.match(/\[\[ZHIXING_V2:([A-Za-z0-9+/=]+)\]\]/)?.[1];if(encoded){const binary=atob(encoded),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}const blocks=text.split(/(?:^|\n)(?:##\s+|学生[：:])/).slice(1);const students=blocks.map(block=>{const lines=block.split('\n').map(x=>x.trim()).filter(Boolean);const s={id:crypto.randomUUID(),name:(lines.shift()||'未命名学生').replace(/^#+\s*/,'').trim(),school:'',targetSchool:'',currentScore:null,targetScore:null,scores:[],custom:[],courseProgress:[],preparations:[],nextLesson:'',focusContent:''};let section='profile';for(const line of lines){if(/^###\s*考试成绩|^考试成绩[：:]?$/.test(line)){section='scores';continue}if(/^###\s*课程进度|^课程进度[：:]?$/.test(line)){section='course';continue}if(/^###\s*教学备忘|^教学备忘[：:]?$/.test(line)){section='notes';continue}if(/^###\s*其他信息|^其他信息[：:]?$/.test(line)){section='custom';continue}const clean=line.replace(/^[-*]\s*/,'');if(section==='scores'&&clean.includes('｜')){const [date,label,score]=clean.split('｜').map(x=>x.trim());if(date&&label&&!Number.isNaN(Number(score)))s.scores.push({date,label,score:+score});continue}if(section==='scores'&&/^\|/.test(clean)){const cells=clean.split('|').map(x=>x.trim()).filter(Boolean);if(cells.length>=3&&!Number.isNaN(Number(cells[2])))s.scores.push({date:cells[0],label:cells[1],score:+cells[2]});continue}if(section==='course'&&clean!=='暂无'&&!clean.startsWith('附件：')){const m=clean.match(/^(.+?)[：:]\s*(.+)$/);s.courseProgress.push(m?{date:m[1],text:m[2]}:{date:'',text:clean});continue}const pairs=[['就读学校','school'],['目标学校','targetSchool'],['目前分数','currentScore'],['目标分数','targetScore'],['下节课要讲的内容','nextLesson'],['着重要听的内容','focusContent']];let matched=false;for(const [label,key] of pairs){const value=textValue(clean,label);if(value!==''||clean.startsWith(label+'：')||clean.startsWith(label+':')){s[key]=key.includes('Score')?(value||null):value;matched=true;break}}if(section==='custom'&&!matched&&clean!=='暂无'){const m=clean.match(/^(.+?)[：:]\s*(.+)$/);if(m)s.custom.push({key:m[1],value:m[2]})}}return s}).filter(s=>s.name&&s.name!=='未命名学生');if(!students.length)throw new Error('未识别到学生档案；请使用本应用导出的 Markdown 或文字文件');return {students,activeId:students[0].id}}
function parsePortableTextBackup(text){
  const encoded=text.match(/\[\[ZHIXING_V2:([A-Za-z0-9+/=]+)\]\]/)?.[1];
  if(encoded){const binary=atob(encoded),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
  const blocks=text.split(/(?:^|\n)(?:##\s+|学生[：:])/).slice(1);
  const students=blocks.map(block=>{
    const lines=block.split('\n').map(value=>value.trim()).filter(Boolean);
    const s={id:crypto.randomUUID(),name:(lines.shift()||'未命名学生').replace(/^#+\s*/,'').trim(),school:'',targetSchool:'',currentScore:null,targetScore:null,scores:[],custom:[],courseProgress:[],preparations:[],nextLesson:'',focusContent:''};
    let section='profile',lastRecord=null;
    const addRecord=(list,clean)=>{const match=clean.match(/^(.+?)[：:]\s*(.*)$/),date=match?.[1]||'',raw=match?.[2]||clean,detail=raw.match(/^(.*)（([^（）]*)）$/);const item={date,title:(detail?.[1]||raw).trim(),content:(detail?.[2]||'').trim(),files:[]};list.push(item);lastRecord=item};
    for(const line of lines){
      if(/^###\s*考试成绩|^考试成绩[：:]?$/.test(line)){section='scores';lastRecord=null;continue}
      if(/^###\s*备课记录|^备课记录[：:]?$/.test(line)){section='preparations';lastRecord=null;continue}
      if(/^###\s*课程进度|^课程进度[：:]?$/.test(line)){section='course';lastRecord=null;continue}
      if(/^###\s*教学备忘|^教学备忘[：:]?$/.test(line)){section='notes';lastRecord=null;continue}
      if(/^###\s*其他信息|^其他信息[：:]?$/.test(line)){section='custom';lastRecord=null;continue}
      const clean=line.replace(/^[-*]\s*/,'');
      if(clean==='---'||clean==='暂无')continue;
      if(clean.startsWith('附件：')||clean.startsWith('附件:')){
        if(!lastRecord)continue;
        const parts=textValue(clean,'附件').split('｜').map(value=>value.trim()).filter(Boolean),display=parts.shift()||'未命名文件';
        const metadata={path:'',type:'application/octet-stream',size:0};
        for(const part of parts){if(/^路径[：:]/.test(part))metadata.path=part.replace(/^路径[：:]\s*/,'');else if(/^类型[：:]/.test(part))metadata.type=part.replace(/^类型[：:]\s*/,'')||metadata.type;else if(/^大小[：:]/.test(part))metadata.size=Number(part.replace(/^大小[：:]\s*/,''))||0;else if(!metadata.path)metadata.path=part}
        lastRecord.files.push({name:display.split(/[\\/]/).pop()||display,relativePath:display,...metadata});continue;
      }
      if(section==='scores'&&clean.includes('｜')){const [date,label,score]=clean.split('｜').map(value=>value.trim());if(date&&label&&!Number.isNaN(Number(score)))s.scores.push({date,label,score:+score});continue}
      if(section==='scores'&&/^\|/.test(clean)){const cells=clean.split('|').map(value=>value.trim()).filter(Boolean);if(cells.length>=3&&!Number.isNaN(Number(cells[2])))s.scores.push({date:cells[0],label:cells[1],score:+cells[2]});continue}
      if(section==='preparations'){addRecord(s.preparations,clean);continue}
      if(section==='course'){addRecord(s.courseProgress,clean);continue}
      const pairs=[['就读学校','school'],['目标学校','targetSchool'],['目前分数','currentScore'],['目标分数','targetScore'],['下节课要讲的内容','nextLesson'],['着重要听的内容','focusContent']];let matched=false;
      for(const [label,key] of pairs){const value=textValue(clean,label);if(value!==''||clean.startsWith(label+'：')||clean.startsWith(label+':')){s[key]=key.includes('Score')?(value||null):value;matched=true;break}}
      if(section==='custom'&&!matched){const match=clean.match(/^(.+?)[：:]\s*(.+)$/);if(match)s.custom.push({key:match[1],value:match[2]})}
    }
    return s;
  }).filter(s=>s.name&&s.name!=='未命名学生');
  if(!students.length)throw new Error('未识别到学生档案；请使用本应用导出的 Markdown 或文字文件');
  return {students,activeId:students[0].id};
}
function openDataCenter(){$('#dataDialog').showModal();renderSyncStatus();setDataMessage('所有档案优先保存在本机浏览器中。')}
$('#sidebarAuthButton').onclick=openDataCenter;
$('#exportBtn').onclick=downloadBackup;
$('#exportMarkdownBtn').onclick=()=>downloadFile(markdownBackup(),`知行家教档案-${today()}.md`,'text/markdown;charset=utf-8','Markdown 档案已开始下载。');
$('#exportTextBtn').onclick=()=>downloadFile(markdownBackup(true),`知行家教档案-${today()}.txt`,'text/plain;charset=utf-8','文字档案已开始下载。');
$('#importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const text=await file.text();let next;try{next=JSON.parse(text)}catch{next=parsePortableTextBackup(text)}if(!Array.isArray(next.students))throw new Error('文件中没有有效学生档案');if(!await ask(`将导入 ${next.students.length} 位学生并覆盖当前本地档案。继续前会自动下载当前 JSON 备份。`,{title:'导入并覆盖档案',danger:true}))return;downloadBackup();state=window.Zhixing.Model.ensureIds({students:next.students,activeId:next.activeId||next.students[0]?.id||null,updatedAt:new Date().toISOString()});save();render();setDataMessage(`已导入 ${state.students.length} 位学生的档案。`)}catch(err){setDataMessage(`导入失败：${err.message}`,true)}finally{e.target.value=''}});
function setAuthMessage(message,error=false){const el=$('#authMessage');el.textContent=message;el.style.color=error?'#b54d42':''}
function openAuth(){const f=$('#cloudForm');f.reset();f.elements.auto.checked=cloud.auto!==false;markClean(f);$('#logoutBtn').hidden=!cloud.userEmail;setAuthMessage(cloud.userEmail?`当前已登录：${cloud.userEmail}`:'');$('#cloudDialog').showModal()}
function confirmCloseAuth(){return closeFormDialog($('#cloudDialog'),$('#cloudForm'),'关闭登录窗口吗？已填写的账号信息不会保留。')}
$('#openCloudSettings').onclick=openAuth;
$('#emptyLoginButton').onclick=openAuth;
$('#closeCloudDialog').onclick=confirmCloseAuth;$('#cancelCloudDialog').onclick=confirmCloseAuth;
$('#cloudDialog').addEventListener('cancel',e=>{e.preventDefault();confirmCloseAuth()});
async function logout(){if(!await ask('这台设备上的学生档案缓存、待上传文件和未同步更改都会被清除，但云端档案不会删除。',{title:'退出账号并清除本机数据',danger:true}))return;const {error}=await supabaseClient.auth.signOut({scope:'local'});await window.Zhixing.Sync.stop();if(realtimeChannel)await supabaseClient.removeChannel(realtimeChannel);realtimeChannel=null;syncEngine='local';await window.Zhixing.Database.wipe();state={students:[],activeId:null,schemaVersion:2};localStorage.removeItem(storeKey);cloud={auto:cloud.auto,lastSync:null,userEmail:''};localStorage.setItem(cloudKey,JSON.stringify(cloud));$('#cloudDialog').close();if($('#dataDialog').open)$('#dataDialog').close();render();if(error)console.warn('云端会话通知失败，本机数据已清除：',error.message)}
$('#logoutBtn').onclick=logout;$('#logoutFromDataBtn').onclick=logout;
$('#authModeBtn').onclick=()=>{authRegister=!authRegister;$('#authTitle').textContent=authRegister?'注册同步账号':'登录云端';$('#authSubmitBtn').textContent=authRegister?'注册并继续':'登录并同步';$('#authModeBtn').textContent=authRegister?'已有账号？登录':'没有账号？注册';$('#cloudForm').elements.password.autocomplete=authRegister?'new-password':'current-password';setAuthMessage('')};
$('#resendConfirmBtn').onclick=async()=>{const email=$('#cloudForm').elements.email.value.trim();if(!email){setAuthMessage('请先填写注册时使用的邮箱地址。',true);return}try{const {error}=await supabaseClient.auth.resend({type:'signup',email,options:{emailRedirectTo:appRedirectUrl}});if(error)throw error;setAuthMessage('确认邮件已重新发送，请同时检查垃圾邮件箱。')}catch(err){setAuthMessage(`发送失败：${err.message}`,true)}};
$('#cloudForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const f=e.currentTarget,email=f.elements.email.value.trim(),password=f.elements.password.value;try{if(authRegister){const {data,error}=await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:appRedirectUrl}});if(error)throw error;if(!data.session){setAuthMessage('注册成功，请到邮箱确认后再登录。');return}}else{const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error}cloud={...cloud,auto:f.elements.auto.checked,userEmail:email};localStorage.setItem(cloudKey,JSON.stringify(cloud));await startRealtime();await syncCloud('push',true);$('#cloudDialog').close();render();if(!$('#dataDialog').open)$('#dataDialog').showModal();setDataMessage('登录成功，现已按记录自动同步。')}catch(err){setAuthMessage(`操作失败：${err.message}`,true)}});
$('#pushBtn').onclick=()=>syncCloud('push');$('#pullBtn').onclick=()=>syncCloud('pull');
async function restoreSession(){if(!supabaseClient)return;const {data:{user}}=await supabaseClient.auth.getUser();if(user){cloud.userEmail=user.email||'';localStorage.setItem(cloudKey,JSON.stringify(cloud));await startRealtime();render();syncCloud('pull',true)}}
$('#scoreDialog').querySelectorAll('[value="cancel"]').forEach(button=>{button.type='button';button.onclick=()=>closeFormDialog($('#scoreDialog'),$('#scoreForm'),'放弃尚未记录的考试成绩吗？')});
$('#scoreDialog').addEventListener('cancel',event=>{event.preventDefault();closeFormDialog($('#scoreDialog'),$('#scoreForm'),'放弃尚未记录的考试成绩吗？')});
$('#customDialog').addEventListener('cancel',event=>{event.preventDefault();closeCustomDialog()});
$('#prepDialog').addEventListener('cancel',event=>{event.preventDefault();closePrepDialog()});
$('#courseDialog').addEventListener('cancel',event=>{event.preventDefault();closeCourseDialog()});
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target!==dialog)return;if(dialog.id==='studentDialog')confirmCloseStudent();else if(dialog.id==='cloudDialog')confirmCloseAuth();else if(dialog.id==='customDialog')closeCustomDialog();else if(dialog.id==='prepDialog')closePrepDialog();else if(dialog.id==='courseDialog')closeCourseDialog();else if(dialog.id==='scoreDialog')closeFormDialog(dialog,$('#scoreForm'),'放弃尚未记录的考试成绩吗？');else if(dialog.id!=='confirmDialog')dialog.close('cancel')}));
async function bootstrap(){state=await window.Zhixing.Database.start(state);localStorage.setItem(storeKey,JSON.stringify(state));render();await restoreSession();renderSyncStatus()}
window.addEventListener('resize',()=>{if(active())drawChart((active().scores||[]).slice().sort((a,b)=>a.date.localeCompare(b.date)))});bootstrap().catch(err=>{console.error(err);setDataMessage(`启动失败：${err.message}`,true);render()});
